project:
  type: website
  output-dir: docs

website:
  title: "andrew-miller-econ.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- about.qmd
      - text: "CV"
        href: media/AndrewMillerCV_full.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

