---
title: "Research"
---

### [Policies to promote wildlife conservation in a spatially heterogeneous landscape](papers/optimal_pol_20240424.pdf)

 (with Daniela Miteva and Sathya Gopalakrishnan)
 
 **Abstract:**
 
> Effective payments for conservation are an important tool to provide transfers from those who derive utility from wildlife involved in human-wildlife conflict and those who bear the economic costs, in order to reduce poaching and promote coexistence. We consider the cost effectiveness of payment schemes across two management goals: poaching reduction and farmer welfare compensation. We build upon previous models to consider how these payments should be applied over space when farmers face heterogeneous depredation risk and thus heterogeneous incentives to poach wildlife. We compare commonly used uniform \textit{ex-post} compensation to spatially targeted compensation, finding that poaching can be reduced further by targeted payments given a limited government agency budget. Regarding the management goal of transfers to livestock owners to promote tolerance, we find that ``payments for presence'' may be preferred in some settings to increase farmer welfare without distorting stocking decisions. Our work suggests that wildlife managers should consider the use of each of these types of payments, dependent on key parameters in each particular setting, and that careful analysis of a particular setting is important before the implementation of a program.

[Link to PDF](papers/optimal_pol_20240424.pdf) 

---

### [The value of forests in reducing malaria mortality in India](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/9AEBE5519179F762AC411F7887DD1ADA/S1355770X25000075a.pdf/the-value-of-forests-in-reducing-malaria-mortality-in-india.pdf)

**Authors:** Daniela A. Miteva, Yu Shing (Samuel) Cheng, Andrew Miller and Sathya Gopalakrishnan 

**Published In:** *Environment and Development Economics*, Published online 2025:1-19. doi:10.1017/S1355770X25000075 

**Abstract:**

> Malaria still poses significant risks, especially in India. In addition to averting behaviors, forests may help reduce mosquitoes in rural areas and, thus, the malaria incidence and mortality. However, the evidence is still scarce about the magnitude and value of this ecosystem service. To address this gap, we use a panel dataset for 2013–2015 and evaluate the impact of forest loss on malaria morbidity in India's rural areas. We find that, on average, the loss of 1 km2 of forest resulted in 0.16 additional deaths per 100,000 people. This translates into marginal values of forests for reducing malaria mortality of, at least, \$1.26–85.9/ha/year in 2015 US$. Our results suggest that combining forest conservation and traditional anti-malaria policies like indoor spraying and insecticide-treated nets may be an effectual way to mitigate the malarial burden in India and elsewhere and offer insights about the value of potential payments for ecosystem services.

[Link to Published Version (PDF)](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/9AEBE5519179F762AC411F7887DD1ADA/S1355770X25000075a.pdf/the-value-of-forests-in-reducing-malaria-mortality-in-india.pdf) | [Link to Journal Website](https://www.cambridge.org/core/journals/environment-and-development-economics/article/value-of-forests-in-reducing-malaria-mortality-in-india/9AEBE5519179F762AC411F7887DD1ADA)

---

### [The Role of Forests in Reducing the Incidence of Acute Respiratory Infections: Evidence from India](papers/forests_and_ari_manuscript.pdf)

(with Daniela Miteva and Sathya Gopalakrishnan)

[Link to PDF](papers/forests_and_ari_manuscript.pdf) 

### [Storage as a determinant of market participation:Evidence from northern Ghana](papers/Ghana_storage_manuscript.pdf)

(with Daniela Miteva)

[Link to PDF](papers/Ghana_storage_manuscript.pdf)

---
